name: "CORS Misconfiguration Factual Cluster"
description: "Multiple tools detected patterns consistent with a CORS misconfiguration."
confidence: 0.90
co_occurring_facts:
  - tool: "patterns"
    pattern: "Access-Control"
  - tool: "security"
    pattern: "wildcard"
  - tool: "framework_detector"
    pattern: "cors"